Settings:
  Settings_1:
    setting: poolname
    value: 'Euro 2012'
    description: poolname_description
  Settings_2:
    setting: version
    value: '1.0 Alpha'
    description: version_description
  Settings_3:
    setting: points_for_goals
    value: '3'
    description: points_for_goals_description
  Settings_4:
    setting: points_for_wdl
    value: '3'
    description: points_for_wdl_description
  Settings_5:
    setting: points_for_exact_score
    value: '5'
    description: points_for_exact_score_description
  Settings_6:
    setting: points_for_team_qf
    value: '7'
    description: points_for_team_qf_description
  Settings_7:
    setting: points_for_team_sf
    value: '11'
    description: points_for_team_sf_description
  Settings_8:
    setting: points_for_team_f
    value: '13'
    description: points_for_team_f_description
  Settings_9:
    setting: points_for_champion
    value: '19'
    description: points_for_champion_description
  Settings_10:
    setting: view_other_users
    value: '1'
    description: view_other_users_description
  Settings_11:
    setting: use_cards
    value: '0'
    description: use_cards_description
  Settings_12:
    setting: server_time_offset_utc
    value: '3600'
    description: server_time_offset_utc_description
  Settings_13:
    setting: user_activation
    value: '1'
    description: user_activation_description
  Settings_14:
    setting: admin_email
    value: admin@example.com
    description: admin_email_description
